---
- name: Update the .bashrc to set SPARK_HOME
  lineinfile:
    dest=/etc/environment
    line="export SPARK_HOME=/usr/lib/spark"
    regexp="export SPARK_HOME=/usr/lib/spark"
    owner=vagrant
    state=present
    insertafter=EOF
    create=True
